### ISSUE TITLE
Is the license GPL, LGPL, or something else?

### ISSUE THREAD

**Issue by kenakofer** [moddevices/mod-tal-noisemaker#10]
Hello! Thank you for making this port!

I'm considering incorporating TAL into a plugin for Unity, which, as I understand it, is only possible legally if TAL is LGPL or something more permissive.

I see in the docs/ folder that there is both a GPL and LGPL license there. Is the license GPL, LGPL, or something else?

I understand that JUCE is included in TAL, and that [JUCE has it's own license conditions](https://juce.com/juce-6-licence). I'm primarily uncertain about the non-JUCE components.

Thanks!

**Comment by falkTX** [comment]
That page from JUCE is awful, typical business practice to lead away from the open-source option.

TAL and the JUCE version inside are GPL.
This repo comes initially from https://github.com/DISTRHO/DISTRHO-Ports

**Comment by kenakofer** [comment]
Thanks!
