### ISSUE TITLE
default patch

### ISSUE THREAD

**Issue by ssj71** [moddevices/mod-tal-noisemaker#7]
the default patch of the noisemaker is pretty decent (just pull the cutoff down a little) but its not in the list of presets. I wanted to get back to that after tweaking a bunch and realized I needed to remove and add the plugin again. 

thanks for bringing this to mod. I want more synths. :)

**Comment by BramGiesen** [comment]
@ssj71 , Thank you for your suggestion. I think it indeed would be nice to add it to the preset list. I'm going to add it somewhere next week and do an update in the plugin store.
